### ISSUE TITLE
use the types maps in derived generators

### ISSUE THREAD

**Issue by lacourte** [esa/CCSDS_MO_StubGenerator#16]
Hi,

I need to browse through the list of types to get all the types compliant to a given abstract type.
I could use the enumTypesSet/allTypesMap/compositeTypesMap/attributeTypesMap tables, but they are declared private. So they are not accessible in my class derived from GeneratorBase.

Could those tables be opened to subclasses and declared as protected ?
Is there a better way to get what I am looking for ?

Thank you

**Comment by SamCooper** [comment]
Pull in your change for this
