### ISSUE TITLE
Maven bundle 1.4 is incomplete

### ISSUE THREAD

**Issue by gbonnefille** [esa/CCSDS_MO_StubGenerator#17]
Hi,

Trying to run the examples, I faced to the following error:

`[ERROR] Failed to execute goal int.esa.ccsds.mo:StubGenerator:1.4:generate (default) on project MAL_DEMO: Execution default of goal int.esa.ccsds.mo:StubGenerator:1.4:generate failed: A required class was missing while executing int.esa.ccsds.mo:StubGenerator:1.4:generate: esa/mo/xsd/SendOperationType`

After investigation, it seems that the StubGenerator_Interfaces-1.4.jar uploaded in the Maven central does not contains the SendOperationType.

Switching to the 1.2 version solves the problem.

Perhaps the 1.4 should be regenerated and uploaded again? Or perhaps a new 1.5?

**Comment by SamCooper** [comment]
Sorry, only just seen this. The classes you are after are contained in:

  <groupId>int.esa.ccsds.mo</groupId>
  <artifactId>XML_JAXB</artifactId>
