### ISSUE TITLE
Relax type expected for adaptor argument in service's stub (in Java)

### ISSUE THREAD

**Issue by gbonnefille** [esa/CCSDS_MO_StubGenerator#20]
When generating the ServiceStub's methods, the expected type of the adapter is really specific. For example, when generating `ParameterStub` (from MC Area) the `asyncGetValue` method expect a `ParameterAdapter`.

While this is semantically exact (if we request a Parameter service, a natural user expect Parameter related returns), such contract avoid usage of more generic adapter. For example, one user can wish to pass an adapter reacting at `submitAckReceived` level only, just because such adapter is easily reusable with many services.

Is it possible to revise the generator to relax the type expected for the adapter arguments, and use `MALInteractionListener`?
Please, note that such change keep the current written code correct.

**Comment by SamCooper** [comment]
This would need to be a change on the Java MAL API specification, can you raise it there please:

https://github.com/SamCooper/JAVA_SPEC_RIDS/issues

**Comment by gbonnefille** [comment]
Issue opened: https://github.com/SamCooper/JAVA_SPEC_RIDS/issues/25
