### ISSUE TITLE
Fix the createMultiReturnType

### ISSUE THREAD

**Issue by CesarCoelho** [esa/CCSDS_MO_StubGenerator#21]
This method should generate the objects based on their corresponding field names:
https://github.com/esa/CCSDS_MO_StubGenerator/blob/master/GEN_JAVA/src/main/java/esa/mo/tools/stubgen/GeneratorLangs.java#L2358

Please also update the Getters and Setters!

At the moment we get something like:
    public Long getBodyElement0();
    public void setBodyElement1(Long __newValue);

**Comment by SamCooper** [comment]
This is related to https://github.com/SamCooper/JAVA_SPEC_RIDS/issues/3

We could add in extra methods to for the named versions, so we'd have:

getBody0()

and

getMyField()

Would that work?

**Comment by CesarCoelho** [comment]
Yap, that would be ok.
I would suggest to also add the deprecated annotation on the old methods, e.g.:
@Deprecated
getBody0()

This would allow backward compatibility and flag the implementer to use the named versions.

**Comment by CesarCoelho** [comment]
Moved here: https://github.com/esa/mo-services-java/issues/6

Closed!
