### ISSUE TITLE
Enumeration to UOctet

### ISSUE THREAD

**Issue by CesarCoelho** [esa/CCSDS_MO_StubGenerator#22]
Some fields in the M&C book, use the UOctet type to hold possible enumerations. So:
validityState of the ParameterValue
category of the AggregationDefinitionDetails
category of the ActionDefinitionDetails

This was done to allow the use of custom states in those fields. (or mission-specific)
The Enumerations at the moment do not support a direct AggregationCategory.toUOctet() method and so, this is what we currently do:
        aDef.setCategory(new UOctet((short) category.getOrdinal()));

Having a direct category.toUOctet() would avoid the above.

Please add on the Generator the possibility to get directly a UOctet type from Enumerations.

**Comment by SamCooper** [comment]
This is a Java API issue so can you add this in to the Java API issues and reference this issue please.
