### ISSUE TITLE
Include the relevant XML service specification files in the generated API JARs

### ISSUE THREAD

**Issue by pabrabbin** [esa/CCSDS_MO_StubGenerator#23]
It would be useful to include the relevant XML service specification files in the generated API JARs.

This would provide a simple, definitive way to see the exact XML service specification the generated stubs correspond to.

These files are not very big, and XML compresses very well, so the increase in size would be minimal.

**Comment by CesarCoelho** [comment]
This would also make it easier for the getServiceXML operation in terms of implementation.

**Comment by SamCooper** [comment]
Done
