### ISSUE TITLE
No response message sent if response message body is declared empty

### ISSUE THREAD

**Issue by S-Gaertner** [esa/CCSDS_MO_StubGenerator#5]
Happy new year, Sam!

Unfortunately I found another issue with the StubGenerator:

When a service declares a REQUEST operation with an empty message body for the response (e.g. testEmptyBody operation of DataTest service in MALPrototype.xml), no response is sent at all. The generated code (DataTestInheritanceSkeleton.java:160 or DataTestDelegationSkeleton.java:162) lacks an `interaction.sendResponse()` statement.

I don't know if the same behaviour occurs for other interaction patterns as well if they define an empty message body.

**Comment by SamCooper** [comment]
Weird!

I'll add some tests to the MAL testbed  to cover these.

**Comment by SamCooper** [comment]
Ok, fixed in my code base, just running some tests before committing the change.

**Comment by SamCooper** [comment]
Closed in b343fae07f9f0cbfcc1cdcb2f5688c350bd6ad5d
