### ISSUE TITLE
generator parsing options

### ISSUE THREAD

**Issue by lacourte** [esa/CCSDS_MO_StubGenerator#8]
The StubGenerator.main defines options -r and -R to specify the reference directories.
Both options are parsed with an equalsIgnoreCase() call, making the -R option never set.

By the way I needed to set the -R option, even with no xsd reference file, because the xsdRefDirectory field otherwise remains at null, and then calling loadXsdSpecifications fails on line:
if (directory.exists()).

Thank you

**Comment by SamCooper** [comment]
Good spot, I'll get that fixed.

Do you need to call it from the command line or would it be preferable to invoke it programatically?

The 1.3 version now adds a way of invoking it directly.

**Comment by lacourte** [comment]
Actually I want to debug the execution from within eclipse.
The only way I know to do that is to start a debug session with the StubGenerator project main, setting the arguments.

**Comment by SamCooper** [comment]
I can fix this quickly in the code and push it to here but it won't appear in Maven Central until I do another release.

Would that be ok?

**Comment by lacourte** [comment]
Yes it is fine.
I applied a patch locally and recompiled so I can work.
I am in no hurry for the fix.
Thank you.
