### ISSUE TITLE
looking for the parent of a composite

### ISSUE THREAD

**Issue by lacourte** [esa/CCSDS_MO_StubGenerator#9]
This issue comes from code reading. It has not been validated with a reference spec.

The parent of a composite is search for in function createCompositeClass (GeneratorLang.java line 1882). It is not stored if the declared parent is named "Composite". However the area name is not checked.
It is certainly dangerous to name an abstract composite type "Composite" in a specific area, but it looks like it is legal. I believe the above code will fail in that case.

**Comment by SamCooper** [comment]
Yes, you are correct, I think there are a couple of places where this kind of incomplete check is made.
